### ISSUE TITLE
No `dist` files since 0.0.3

### ISSUE THREAD

**Issue by wasp898** [valjic1/ts-catch-decorator#1]
Hello @valjic1, it seems that since the upgrade to 0.0.3 the project does not export `.js` files in the `dist` folder anymore.
For instance, we used to rely on `catch-decorator-ts/dist/index.es.js` to be available in `node_modules`, but it's not there anymore.
Is this expected or is it a bug?

**Comment by valjic1** [comment]
Hey @wasp898, looks like I've accidentally added `dist/` folder to `.gitignore`. I've just published it again with version number `0.0.5` including `ts-node` and `typescript` packages versions updated. Everything should work fine again.
